### ISSUE TITLE
YouTubePlayerView usually doesn't resize content vertically.

### ISSUE THREAD

**Issue by jackpal** [SvenTiigi/YouTubePlayerKit#10]
## YouTubePlayerKit Environment

- YouTubePlayerKit version: 1.1.3, but issue was seen in earlier versions too.
- macOS version: 12.0
- Xcode version: 13.2 beta, but also earlier versions
- Dependency manager (SPM, Manually): SPM

## What did you do?

1. Clone https://github.com/jackpal/AmahTV app on an iPad mini (reproduces on simulator iOS 15.0)
2. git checkout resize-bug
3. Build and run the app on an iPad. (The first time you do this you will have to update the bundleID and team)
4. Tap on "Settings" tab to bring up a two-pane UI, where the left pane is a list of channels, and the right pane is a player.
5. Tap on one of the channels (any one) in the left pane to choose a channel.
6. If the channel doesn't start playing automatically, tap on the play button.
7. Tap on the "hide left pane" button in the top left to hide the left panel

## What did you expect to happen?

I expected the YouTubePlayer to expand to fill the screen.

## What happened instead?

The YouTubePlayer stays the same size that it was when the left pane was visible.

This bug reproduces most of the time -- but not always. Once in a while the YouTubePlayer resizes to fill the new space. Seem like it might be a race condition.

**Comment by jackpal** [comment]
I simplified the repro steps:

1. Clone https://github.com/jackpal/AmahTV app on an iPad mini (reproduces on simulator iOS 15.0)
2. git checkout resize-bug
3. Build and run the app on an iPad. (The first time you do this you will have to update the bundleID and team)
4. Put iPad in landscape mode
5. Run app
6. Tap on list of videos at top of app to choose a different video
7. Rotate to portrait
8. Rotate back to landscape

Expected

Video fills screen

Actual

Video is still the size that it was in portrait mode

**Comment by jackpal** [comment]
A work-around seems to be to modify YouTubePlayer.html's window.onResize as follows:

        // On window resize
        window.onresize = () => {
            setTimeout(() => {
                // Check if player is available
                if (player) {
                    // Set Player size
                    player.setSize(
                        window.innerWidth,
                        window.innerHeight
                    );
                }
            }, 1);

**Comment by SvenTiigi** [comment]
Hey @jackpal

Please check out the [`develop`](https://github.com/SvenTiigi/YouTubePlayerKit/tree/develop) branch which contains a fix (https://github.com/SvenTiigi/YouTubePlayerKit/commit/37733bc2a0db43857eca2c1d856e2dc27295a24f) that should resolve this issue.

Please let me know if this fix also works on your side ✌️

**Comment by jackpal** [comment]
Using the tip of the develop branch did fix the issue for me. Thanks!

**Comment by SvenTiigi** [comment]
The fix is now included in the latest release [1.1.4](https://github.com/SvenTiigi/YouTubePlayerKit/releases/tag/1.1.4)
