### ISSUE TITLE
Support Privacy Enhanced Mode

### ISSUE THREAD

**Issue by jackpal** [SvenTiigi/YouTubePlayerKit#11]
# Motivation

It seems that YouTube has an option for "privacy enhanced" embedded videos:

https://support.google.com/youtube/answer/171780?hl=en#zippy=%2Cturn-on-privacy-enhanced-mode

Please consider supporting privacy enhanced embedded videos as a configuration option.

(I haven't investigated whether this is an easy change or not.)

**Comment by SvenTiigi** [comment]
Hi @jackpal 

The "privacy enhanced" mode is currently not a configuration parameter of the YouTube Player iFrame API (https://developers.google.com/youtube/player_parameters)

The "privacy enhanced" mode is making use of the `Same-Origin-Policy` (https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) which prevents the sharing of Cookies inside the embedded YouTubePlayer iFrame as the host is different.

As every iOS App is living in a sandbox the `WKWebView` has no direct access to the Cookies stored in the Safari or any other Browser which is one reason why `SFSafariViewController` exists. 
Meaning there is no way that Cookies stored in the Safari Browser can be accessed from an `WKWebView` which a developer of an app controls which results in an always "privacy enhanced" mode as no Cookies will be shared.

**Comment by jackpal** [comment]
Sounds good, thanks!
