### ISSUE TITLE
Captions when in fullscreen

### ISSUE THREAD

**Issue by pfandrade** [SvenTiigi/YouTubePlayerKit#110]
### Is your feature request related to a problem?

Yes, captions only show when when the player is not in fullscreen (using either .system or .web for the fullscreen option).

### What solution would you like?

Ideally when the user switches to fullscreen he would still be able to see the captions.

### What alternatives have you considered?

I haven't considered an alternative.

**Comment by SvenTiigi** [comment]
The rendered user interface is controlled and managed by the [YouTube Player iFrame API](https://developers.google.com/youtube/iframe_api_reference) please consider to open a bug report at https://developers.google.com/youtube/players/support

**Comment by kiddosai** [comment]
Actually is there a way to turn off captions when *not* in fullscreen?
