### ISSUE TITLE
Apple Store

### ISSUE THREAD

**Issue by gregorybesson** [SvenTiigi/YouTubePlayerKit#12]
Just wanted to thank you @SvenTiigi:

Thanks to your library, I've been able to develop and publish my app on the Apple store!

**Important**: I've had to add the Youtube ToS link for my app to be published. (see here : https://github.com/youtube/youtube-ios-player-helper/issues/399#issuecomment-867539604)

(The published app is Punchline: Sounds fun: https://apps.apple.com/us/app/punchline-sounds-fun/id1582837896 if you want to have a look on the way _YoutubePlayerKit_ is integrated) 

I think that this post could be of interest for those wanting to publish their app with your library.

Thanks again. I've struggled a bit to start and stop video with subseconds precision, but I've succeeded. If anyone needs info, just ask :)

Greg

**Comment by SvenTiigi** [comment]
Hi @gregorybesson

You are welcome 🙂
Great to hear your App was successfully reviewed and is now available in the App Store 👍 

I will add your tip which you have linked to the `README` of YouTubePlayerKit to inform the developers who are making use of the `YouTubePlayerKit` to include the Terms of Service URL of YouTube to the App Store review notes.

**Comment by acosmicflamingo** [comment]
OH YEAHHHHHHHH!!!

Congrats @gregorybesson for making it to the App Store, and thanks @SvenTiigi for making such a great framework! 🥇 🥇 🥇

**Comment by SvenTiigi** [comment]
ReadMe now includes a  `App Store Review` section https://github.com/SvenTiigi/YouTubePlayerKit/commit/0e7c68a50719f62b9af07d56042a3d919720cc8b

Closing this issue for now
Thanks for the hint @gregorybesson

**Comment by gregorybesson** [comment]
You're most welcome @SvenTiigi
