### ISSUE TITLE
Fullscreen API?

### ISSUE THREAD

**Issue by ryangittings** [SvenTiigi/YouTubePlayerKit#13]
# Motivation
I've love to be able to use a custom button to make the player full-screen, without needing to use the YouTube UI. 

# Solution
Not sure if it's possible, but it'd be a great addition to my custom player.

**Comment by SvenTiigi** [comment]
Hi @ryangittings,

Currently the [YouTube Player iFrame API](https://developers.google.com/youtube/iframe_api_reference) doesn't offer an API to trigger the full-screen view/button programmatically.

One option would be to set the `playInline`  bool property of the `YouTubePlayer.Configuration` to `false`, which would result in an always fullscreen player. 

```swift
let youTubePlayer = YouTubePlayer(
    source: .url("..."),
    configuration: .init(
        playInline: false
    )
)
```

or during runtime:

```swift
youTubePlayer.configuration = .init(playInline: false)
```

> Please note when updating the `YouTubePlayer.Configuration` while the player is playing will result in a reload of the entire YouTubePlayer.

**Comment by SvenTiigi** [comment]
Closing this issue for now due to inactivity.
Please feel free to re-open the issue at anytime.
