### ISSUE TITLE
Small documentation fixes

### ISSUE THREAD

**Issue by hartti** [SvenTiigi/YouTubePlayerKit#20]
## MacOS usage

Add note that one should tick the box for "Outgoing Connections (Client)" on Signing and Capabilities. Otherwise the player always fails.

### 1
In Section "Usage": 
```
autPlay: true
```
should be
```
autoPlay: true
```
### 2
In Section "Configuration" the following does not work
```
let youTubePlayer = YouTubePlayer(
    source: "https://youtube.com/watch?v=psL_5RIBqnY",
    configuration: configuration
)
```
should be
```
let youTubePlayer = YouTubePlayer(
    source: .url("https://youtube.com/watch?v=psL_5RIBqnY"),
    configuration: configuration
)
```

**Comment by SvenTiigi** [comment]
Great find 👍 
 I've just fixed the typos and added a small hint to enable "Outgoing Connections (Client)" for a macOS target.
- https://github.com/SvenTiigi/YouTubePlayerKit/commit/9b541fbe5e57109055d14e9585043051ef5d4308
- https://github.com/SvenTiigi/YouTubePlayerKit/commit/a533a77a1f47094f1be55c72f8795877e9747299
- https://github.com/SvenTiigi/YouTubePlayerKit/commit/2839207b2e6219b28b08f1a1939e8c933a42b40c
