### ISSUE TITLE
Youtube embedded links fail

### ISSUE THREAD

**Issue by Freelenzer** [SvenTiigi/YouTubePlayerKit#24]
Using Youtube embed style api fails. I used: "https://www.youtube.com/embed/m8qvOpcDt1o?rel=0"

**Comment by SvenTiigi** [comment]
Hi @Freelenzer,

Thanks for your bug report.
I have identified the problem and pushed the bug fix https://github.com/SvenTiigi/YouTubePlayerKit/commit/d86113121023a9b478e73e49b3c2d59af1b9e4b0

Please let me know if the the new version [`1.1.10`](https://github.com/SvenTiigi/YouTubePlayerKit/releases/tag/1.1.10)  of YouTubePlayerKit fixes your problem ✌️

**Comment by Freelenzer** [comment]
Thanks. That fixes the issue :)
