### ISSUE TITLE
Support also Vimeo videos

### ISSUE THREAD

**Issue by hartti** [SvenTiigi/YouTubePlayerKit#25]
# Motivation
Even though Vimeo is not as popular online video service as YouTube, there are still a lot of content available there which is not available on YouTube. Having a single video player for both of the services would simplify app development and allow to show videos from both services 

# Solution
Would be nice to just provide a link to the player (either YouTube or Vimeo) and the system takes care of everything else and provides same controls (as much as possible) independent on where the video is located

# Additional context 
No additional comments at this time - and no idea how complex implementing this would be

**Comment by SvenTiigi** [comment]
Hey @hartti,

Currently there is no plan in adding support for Vimeo videos to the YouTubePlayerKit as the focus of this Swift Package is tightly coupled to the YouTubePlayer iFrame API.

Please have a look at other repos on GitHub which are more suitable in playing Vimeo videos:
https://github.com/search?q=vimeo+language%3Aswift

**Comment by hartti** [comment]
Thanks for the reply! Makes complete sense to focus on YT.
