### ISSUE TITLE
Vice Reconition with YoutubePlayerKit via AirPod Pro

### ISSUE THREAD

**Issue by ymatt345** [SvenTiigi/YouTubePlayerKit#26]
Hello,
I need to play Youtube and recognize my voice at same time.
I could succeed to recognize my voice when the system speaker was selected for Youtube play.
How ever the recognition of my voice was failed when the bluetooth hands free device such as AirPod Pro was selected for Youtube play. 
If I play sound using AVPlayer and  AVAudioPlayer and recognize my voice at same time, the recognition of my voice was succeeded via bluetooth hands free device.
Please advice me how to pass my voice from BLE hands free device as the sound input when specifying allowBluetooth option to AVAudioSession.

Before playing YoutubePlayerKit, audioSession was set as follows 
        do {
             audioSession = AVAudioSession.sharedInstance()
             try audioSession.setCategory(.playAndRecord, mode: .measurement, options: .allowBluetooth)  // Works fine for Youtube sound to BLE speaker but not work for voice input via BLE microphone. 
 / /          try audioSession.setCategory(.playAndRecord, mode: .measurement, options: .duckOthers)   // Works fine for voce input and speaker out
             try AVAudioSession.sharedInstance().setActive(true, options: .notifyOthersOnDeactivation)
           } catch _ {
             handleError(withMessage:"play youtube audio session error")// failed to record
           }
 
And set audioEngine as follows when do voice recognition.
        audioEngine = AVAudioEngine()
        inputNode = audioEngine.inputNode
        inputNode.removeTap(onBus: 0)

        guard let commonFormat = AVAudioFormat(commonFormat: .pcmFormatFloat32, sampleRate: 44100, channels: 2, interleaved: false) else { return }
        let recordingFormat = inputNode.outputFormat(forBus: 0)
          inputNode.installTap(onBus: 0, bufferSize: 1024, format: recordingFormat) { (buffer: AVAudioPCMBuffer, when: AVAudioTime) in
           self.recognitionRequest?.append(buffer)
        }

YouTubePlayerKit version: 1.1.11
macOS version: 12.3.1
Xcode version: 13.4

Best regards

**Comment by SvenTiigi** [comment]
Hi @ymatt345,

Thanks for opening up an issue.
The described scenario exceeds the context of the YouTubePlayerKit and therefore better been asked on platforms like [StackOverflow](https://stackoverflow.com/)
