### ISSUE TITLE
how can i hide pip moe in this library ?

### ISSUE THREAD

**Issue by cp-rajvi-p** [SvenTiigi/YouTubePlayerKit#27]
# Motivation
> ℹ Please replace this with your motivation. For example if your feature request is related to a problem.

# Solution
> ℹ Please replace this with your proposed solution.

# Additional context 
> ℹ Please replace this with any other context or screenshots about your feature request (optional).
How can i remove pip mode in this Library ?

**Comment by SvenTiigi** [comment]
Hi @cp-rajvi-p,

You can disable `Picture-in-Picture` mode via the [`YouTubePlayer.Configuration`](https://github.com/SvenTiigi/YouTubePlayerKit/blob/main/Sources/Configuration/YouTubePlayer%2BConfiguration.swift) which is passed during instantiation of a `YouTubePlayer`.

```swift
let youTubePlayer = YouTubePlayer(
    source: ...,
    configuration: .init(
        allowsPictureInPictureMediaPlayback: false
    )
)
```

https://github.com/SvenTiigi/YouTubePlayerKit/blob/96b831c0132ad194c568a924d6bf8a4a26f3a517/Sources/Configuration/YouTubePlayer%2BConfiguration.swift#L18-L20

**Comment by cp-rajvi-p** [comment]
Hey
Still i am facing pip mode.

**Comment by cp-rajvi-p** [comment]
how can i hide sub titles of language ?
