### ISSUE TITLE
WWDCKeynote app starts out blank on iPad portrait

### ISSUE THREAD

**Issue by jackpal** [SvenTiigi/YouTubePlayerKit#3]
## YouTubePlayerKit Environment

- YouTubePlayerKit version: 1.1.1
- macOS version: 12.0 beta
- iOS version: 15.0.2
- Xcode version: 13.0
- Dependency manager (SPM, Manually): SPM

## What did you do?

1) Built and ran the WWDCKeynote example on an iPad Mini 6th gen.
2) Started app while the iPad is in portrait mode
3) Tapped on the "< WWDC Keynote" navigation link

## What did you expect to happen?

Expected to see the WWDC videos

## What happened instead?

Heard audio, but the video and most video thumbnailss were blank.

![iPad-portrait](https://user-images.githubusercontent.com/175575/137638653-600648c1-6f61-4c81-920a-3b98690418f4.png)

**Comment by SvenTiigi** [comment]
Closing issue. 
Continued in https://github.com/SvenTiigi/YouTubePlayerKit/issues/4
