### ISSUE TITLE
Disable More Videos

### ISSUE THREAD

**Issue by phcs971** [SvenTiigi/YouTubePlayerKit#30]
Is it possible to remove the More Videos tab when the video is paused? 
<img width="755" alt="image" src="https://user-images.githubusercontent.com/48731731/176762257-003b799c-b9a6-474d-a093-ed4243af2a6e.png">
I could not find any solution and as it is a feature from youtube, it might not be possible, but maybe someone here has encountered something similar.

EDIT: I found out that it doesn't appear when the app is in portrait mode, so I might be doing something in that area.

**Comment by erank3** [comment]
I don't think it possible, those tabs come from YouTube (I assume it is based on the player size).
Even it there was a way to remove them it would violate their TOS.

**Comment by SvenTiigi** [comment]
Hi @phcs971,

Thanks for opening up an issue.
Sadly the YouTube Player iFrame API doesn't provide a parameter to hide the more videos tab.
