### ISSUE TITLE
Passing String into Video ID

### ISSUE THREAD

**Issue by jakeround** [SvenTiigi/YouTubePlayerKit#34]
Hello,

I'm facing an issue passing a String into the `.video(id: "psL_5RIBqnY"),`

I have the YouTube ID being passed via  `let trailer: String` which outputs dynamically in the example the output is **W1waReygdb0** how's the best way to dynamically update the ID for the player? I've attached a screenshot

![Screenshot 2022-08-03 at 20 03 14](https://user-images.githubusercontent.com/31782753/182688806-f85b3ad3-9e7c-4571-a81e-169ffd2c39a2.png)

**Comment by SvenTiigi** [comment]
Hi @jakeround,

How about writing an initializer for your `YouTubeTrailer` struct?

```swift
struct YouTubeTrailer: View {

    private let trailer: String

    private let title: String

    @StateObject
    private var youTubePlayer: YouTubePlayer

    init(trailer: String, title: String) {
        self.trailer = trailer
        self.title = title
        self._youTubePlayer = .init(
            wrappedValue: .init(
                source: .video(id: trailer),
                configuration: .init(
                    autoPlay: true
                )
            )
        )
    }

    var body: some View {
        // ...
    }

}
```

Alternatively, you can pass the `trailer` inside the `body` of your View if you just want to show the video and don't need to interact with the `YouTubePlayer` object directly.

```swift
struct YouTubeTrailer: View {

    let trailer: String

    let title: String
    
    var body: some View {
        VStack {
            Text(title)
            Text(trailer)
            YouTubePlayerView(
                .init(
                    source: .video(id: self.trailer),
                    configuration: .init(
                        autoPlay: true
                    )
                )
            ) { state in
                // ...
            }
        }
        // ...
    }

}
```

**Comment by jakeround** [comment]
Hello @SvenTiigi 

Amazing! That's solved my issue, appreciate the help!

Cheers,
Jake
