### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by SvyatHoly** [SvenTiigi/YouTubePlayerKit#37]
Hello!
<img width="576" alt="Screen Shot 2022-08-18 at 7 28 53 PM" src="https://user-images.githubusercontent.com/43349266/185446894-8bda3891-49aa-4694-99bd-6538e17e84b4.png">

There is a memory leak on swiftUI view appear, the new subscription is created every time.

**Comment by SvenTiigi** [comment]
Hi @SvyatHoly,

The `NSKVONotifying_YouTubePlayerKit.YouTubePlayerWebView` simply represents the Combine based Key-Value-Observation for each instance of the YouTubePlayerWebView and therefore is not representing any kind of memory-leak.

https://github.com/SvenTiigi/YouTubePlayerKit/blob/8c90f96973ef709cda0fbebe3989be49d7fc77bb/Sources/WebView/YouTubePlayerWebView.swift#L101-L124
