### ISSUE TITLE
It is possible to specify a xcode version on CI file?

### ISSUE THREAD

**Issue by kobe-pedroveloso** [SvenTiigi/YouTubePlayerKit#39]
# Motivation
> Most of real world projects aren't updated so often due a lot of reasons. Some of them could delay almost a year to update their Xcodes. So, to keep the ci running on a macOS-latest machine without specifying the xcode version could be very problematic to this kind of users, since it can change anytime, and from a version to another it could stop working on release step.

# Solution
> Specify a xcode version on CI file; Inform this version on README.md and keep it tracked.

# Additional context 
> Maybe count machine upgrades as breaking changes in versioning could be a good move.

**Comment by SvenTiigi** [comment]
Hi @kobe-pedroveloso,

Thanks for you feedback.

The `Package.swift` manifest file already specifies the minimum Swift Tools Version as well as the minimum deployment targets for each platform. Therefore, a reference to a dedicated Xcode version is not needed.

https://github.com/SvenTiigi/YouTubePlayerKit/blob/8c90f96973ef709cda0fbebe3989be49d7fc77bb/Package.swift#L1

https://github.com/SvenTiigi/YouTubePlayerKit/blob/8c90f96973ef709cda0fbebe3989be49d7fc77bb/Package.swift#L7-L9

Of course it would be a good idea to add a `matrix` to the `ci.yml` file to run the tests of the YouTubePlayerKit on the latest as well as the previous macOS version.

https://github.com/SvenTiigi/YouTubePlayerKit/blob/8c90f96973ef709cda0fbebe3989be49d7fc77bb/.github/workflows/ci.yml#L15

**Comment by kobe-pedroveloso** [comment]
Hi! Thank you for the quick answer!

I opened this issue because I was facing a problem during the archive process. The problem was the Xcode version used to build the lib, it was greater than `13.2.1 (13C100)`. Yes, that's a limitation of my project (And it can happen with more people).

But since the CI machine is the macOS-latest this information (Xcode version) isn't clear.

My solution was to find some version of the lib which was specifying the Xcode version on `ci.yml`. I've found the version `1.1.10` which specifies the exactly Xcode version I needed.

https://github.com/SvenTiigi/YouTubePlayerKit/blob/d86113121023a9b478e73e49b3c2d59af1b9e4b0/.github/workflows/ci.yml#L18-L19

Maybe add to the readme file the configuration what this "macOS-latest" machine would be a good idea as well.

**Comment by SvenTiigi** [comment]
The GitHub Action CI Workflow has no effect on the YouTubePlayerKit when including it to another Xcode Project or Swift Package via the Swift Package Manager as the GitHub Action CI Workflow is only used to run the tests. In other words the GitHub Action CI workflow is not part of the YouTubePlayerKit itself.

To check whether you can embed the YouTubePlayerKit or not, you need to check the `swift-tools-version` as well as the minimum deployment target of the [`Package.swift`](https://github.com/SvenTiigi/YouTubePlayerKit/blob/main/Package.swift) Manifest.

**Comment by SvenTiigi** [comment]
Please switch to the [`develop`](https://github.com/SvenTiigi/YouTubePlayerKit/tree/develop) branch and check if this resolves your current archiving issue https://github.com/SvenTiigi/YouTubePlayerKit/commit/48b3716ce316bb67c19b10c4335f356b195dd72e.

**Comment by kobe-pedroveloso** [comment]
Hey @SvenTiigi !
Sorry for the late reply. I've switched to the develop and it worked! 🚀 

Do you know if this version will be release as a tag? :)

Thx!

**Comment by SvenTiigi** [comment]
The fix is now available with the latest version [`1.2.1`](https://github.com/SvenTiigi/YouTubePlayerKit/releases/tag/1.2.1)
