### ISSUE TITLE
I have a question for app store reviews

### ISSUE THREAD

**Issue by yongbeomkwak** [SvenTiigi/YouTubePlayerKit#40]
hell guys!

i try to develop music app about some streamer's with your YouTubePlayerKit and i submit my app to apple store connect
but i rejected for the following reasons:

5.2.3 Audio/Video Downloading: Apps should not facilitate illegal file sharing or include the ability to save, convert, or download media from third-party sources (e.g. Apple Music, YouTube, SoundCloud, Vimeo, etc.) without explicit authorization from those sources. Streaming of audio/video content may also violate Terms of Use, so be sure to check before your app accesses those services. Documentation must be provided upon request.

Can I pass the screening using your package?

please give me a advice...

**Comment by SvenTiigi** [comment]
I can not give a 100% guarantee that the Apple App Store Review allows Apps to make use of the Apple App Store Review Guidelines.

As long as you are using the official APIs and do not include any kind of downloading mechanism or something similar the chances are high that you App passes the review as long as you are including the YouTube Terms of Services in the review notes as described in the ReadMe.

https://github.com/SvenTiigi/YouTubePlayerKit#app-store-review

Please note that I cannot provide any further support in this case.

**Comment by yongbeomkwak** [comment]
is it right where you said?
<img width="1141" alt="스크린샷 2022-09-07 오후 7 23 43" src="https://user-images.githubusercontent.com/48616183/188857862-0ed9c4b0-a195-4cde-a219-cd758f8b1087.png">

**Comment by SvenTiigi** [comment]
Yes!

**Comment by yongbeomkwak** [comment]
Thank you sir .. i forgot that mention..  i will retry submission
