### ISSUE TITLE
Sir I have a question about background play

### ISSUE THREAD

**Issue by yongbeomkwak** [SvenTiigi/YouTubePlayerKit#41]
hello sir! 
I already asked the answer about background play and you  provided a link 
https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/configuring_the_audio_playback_of_ios_and_tvos_apps

but that link is related the AVAudioSession ..
is it possible to play youtubeVideo via AVAudioSession ??? 
how can i play background with your youtubePlayerKit..

**Comment by SvenTiigi** [comment]
Hi @yongbeomkwak,

Background Audio playing is against the YouTube Terms of Services and therefore not supported in the YouTube Player iFrame API which is the underlying web based framework that is used by YouTubePlayerKit
