### ISSUE TITLE
Sir I have a question about  advertisement

### ISSUE THREAD

**Issue by yongbeomkwak** [SvenTiigi/YouTubePlayerKit#42]
If I play YouTube using the package you developed, will the ad revenue be reflected?

**Comment by SvenTiigi** [comment]
Hi @yongbeomkwak,

this question does not fall in the context of the YouTubePlayerKit.
For more information about ads and especially ad revenue take a look at the YouTube Terms of Services.

https://developers.google.com/youtube/terms/api-services-terms-of-service
