### ISSUE TITLE
YouTube Analytics

### ISSUE THREAD

**Issue by mikem011** [SvenTiigi/YouTubePlayerKit#45]
## YouTubePlayerKit Environment

- YouTubePlayerKit version: 1.1.12
- macOS version: 12.6
- Xcode version: 14.0.1
- Dependency manager (SPM, Manually): SPM

## What did you do?

> ℹ When playing videos from within the app, the analytics are not showing up on my YouTube page.  The videos to do show any views.

## What did you expect to happen?

> ℹ I expect my analytics to update based on views from the app

## What happened instead?

> ℹ No analytics are updated

**Comment by SvenTiigi** [comment]
Hi @mikem011,

this issue is a limitation of the underlying YouTube Player iFrame API.
https://developers.google.com/youtube/iframe_api_reference

**Comment by mikem011** [comment]
Thanks for your quick reply.  If analytics is a limitation, what is the purpose of the referrer property?  According to the API docs setting that property should at least tag the external source with the site that is set using the property.  Does that property have no effect?
