### ISSUE TITLE
What to use for channel name?

### ISSUE THREAD

**Issue by richardchui** [SvenTiigi/YouTubePlayerKit#47]
While "iJustine" is working fine, I cannot figure out what name to use for the other channels.  For instance for "Dave2D" or "Bullet Journal", I have tried different variations and still could not get it to work.  Thanks!

**Comment by SvenTiigi** [comment]
Hi @richardchui 

Sadly the YouTube Player iFrame API documentation doesn't provide detailed information about this issue as the channel name is passed to the `user_uploads` parameter when loading the player.
https://developers.google.com/youtube/iframe_api_reference
<img width="969" alt="Bildschirm­foto 2022-12-08 um 17 29 44" src="https://user-images.githubusercontent.com/11733014/206507662-70986aaa-f4b7-45a9-9847-5f58cea7f611.png">
