### ISSUE TITLE
Disable scrolling the player on macOS

### ISSUE THREAD

**Issue by kuglee** [SvenTiigi/YouTubePlayerKit#59]
### What happened?

Hi,

Thanks for the package, it's working great on iOS. However on macOS the player view can be scrolled and a scroll bar is also visible. Is there a way to disable it?
![Névtelen 5](https://user-images.githubusercontent.com/1316211/219872330-8681ad00-ece9-4d6e-9463-b53e61d9d1e5.png)

### What are the steps to reproduce?

Here is a test view:

```swift
  public var youtubePlayerView: some View {
      YouTubePlayerView(YouTubePlayer("https://youtube.com/watch?v=psL_5RIBqnY"))
    .aspectRatio(16 / 9, contentMode: .fit)
  }
``

### What is the expected behavior?

I would expect the scroll gesture to be disabled on the player view .

**Comment by SvenTiigi** [comment]
Hey @kuglee,

Please check out the [`develop`](https://github.com/SvenTiigi/YouTubePlayerKit/tree/develop) branch which I've just updated to also disable scrolling on macOS (https://github.com/SvenTiigi/YouTubePlayerKit/commit/180bbdaeb3241670f61cc098d5f6b92af89090b1)

**Comment by kuglee** [comment]
Thank, it's working.
The only issue I have now is that ```aspectRatio(16 / 9, contentMode: .fit)``` is not always perfect, so sometimes when the window is resized the scrollbars still appear. I don't know if it's possible to hide them or to size the view some other way to keep aspect ratio.

**Comment by kuglee** [comment]
I've experimented with WKWebView. This css should hide the scrollbars:
```html
<style>
  ::-webkit-scrollbar {
       display: none !important;
  }
</style>
```

**Comment by SvenTiigi** [comment]
CSS style has been added with https://github.com/SvenTiigi/YouTubePlayerKit/commit/3370aac5a8c43a4a20dc6dfd27182a6d4f19a633 and will be available with the next release ✌️

**Comment by kuglee** [comment]
Awesome. Thanks.
