### ISSUE TITLE
Is there any way to detect fullscreen events ?

### ISSUE THREAD

**Issue by rijink7** [SvenTiigi/YouTubePlayerKit#61]
Is there any way to detect fullscreen events?

**Comment by SvenTiigi** [comment]
Although YouTubePlayerKit doesn't provide any kind of fullscreen detection API I think you should easily detect the fullscreen mode by subscribing to the [UIWindow.didBecomeHiddenNotification](https://developer.apple.com/documentation/uikit/uiwindow/1621617-didbecomehiddennotification) and [UIWindow.didBecomeVisibleNotification](https://developer.apple.com/documentation/uikit/uiwindow/1621621-didbecomevisiblenotification) using the NotificationCenter.
