### ISSUE TITLE
Is there any way to disable context menu?

### ISSUE THREAD

**Issue by Cyantou** [SvenTiigi/YouTubePlayerKit#62]
### Is your feature request related to a problem?

When I do action long press on View. The context menu will be shown like this:
![context_menu](https://user-images.githubusercontent.com/113324583/222998186-c1dbcf6f-b0af-41d7-9b6e-cddb29c1c147.png)

### What solution would you like?

Is there any option to disable display of that menu?

### What alternatives have you considered?

I tried to using **.highPriorityGesture()** on outside VStack. However, gesture still trigger on to YouTubePlayerView.

**Comment by SvenTiigi** [comment]
Hi @Cyantou,

This overlay is shown and controlled by the underlying YouTube iFrame JavaScript API. 
Sadly the YouTube iFrame JavaScript API doesn't provide a configuration parameter to disable this overlay menu when the user long presses the view.
