### ISSUE TITLE
Is it possible to set origin?

### ISSUE THREAD

**Issue by DusanFM** [SvenTiigi/YouTubePlayerKit#64]
### Is your feature request related to a problem?

It seems that unless origin is set to "origin": "http://www.youtube.com", some videos that are restricted to youtube only will not play in the app.

### What solution would you like?

I would like  for origin to be a property in configuration so that it can be set. In that case It should correspond to the origin parameter in the IFrame API (https://developers.google.com/youtube/player_parameters)

### What alternatives have you considered?

set enableJavascriptAPI to true and just have origin set to "http://www.youtube.com" by default in the config.

**Comment by SvenTiigi** [comment]
Hey @DusanFM,

Please check out the [`develop`](https://github.com/SvenTiigi/YouTubePlayerKit/tree/develop) branch which allows setting the `origin` parameter in the `YouTubePlayer.Configuration`.

**Comment by DusanFM** [comment]
@SvenTiigi
Code-wise It looks really good!

To test it I assume I need to clone the develop branch and create a new instance that will play from that?
This is my first time commenting on a public library so I am a bit unsure of the workflow. so that is the reason why I am wondering.

**Comment by DusanFM** [comment]
BTW, do you know if setting "origin": "http://www.youtube.com/" breaks some of youtube's user condition?

**Comment by SvenTiigi** [comment]
More information about changing the requirement of a dependency can be found here: https://developer.apple.com/documentation/xcode/adding-package-dependencies-to-your-app

In default the `origin` identifier is set to `https://{BUNDLE-ID}` which works perfectly fine but of course I can't guarantee that any other `origin` value also works 100% correct.

Closing this issue for now ✌️
The changes will be available with the next release.

**Comment by SvenTiigi** [comment]
The changes are now available with the latest version [`1.5.0`](https://github.com/SvenTiigi/YouTubePlayerKit/releases/tag/1.5.0)
