### ISSUE TITLE
Ability to control going in and out of fullscreen

### ISSUE THREAD

**Issue by kiddosai** [SvenTiigi/YouTubePlayerKit#70]
### Is your feature request related to a problem?

It seems all actions such as play, mute, ... have been exposed but not fullscreen. 

### What solution would you like?

Maybe something like that?
youTubePlayer.toggleFullscreen
youTubePlayer.isFullscreen

configuration {
 autoFullscreen: true
}

### What alternatives have you considered?

If I use my own Swift view with a UIViewRepresentable WKWebView loading the video URL automatically goes to fullscreen.

**Comment by SvenTiigi** [comment]
Hi @kiddosai,

Unfortunately, there is no API for programmatically launching full-screen mode in either WebKit or the YouTube Player iFrame JS API.
