### ISSUE TITLE
Does not work on macOS Sonoma Version 14.0 (23A339) (Release Candidate)

### ISSUE THREAD

**Issue by stormychel** [SvenTiigi/YouTubePlayerKit#72]
### What happened?

White or black screen and no video playing, no sound either.
Could extract error from YouTubePlayerView state: **webContentProcessDidTerminate**

### What are the steps to reproduce?

**SwiftUI:**

YouTubePlayerView(URL)

### What is the expected behavior?

Show video instead of white or black screen.

**Comment by stormychel** [comment]
Error: webContentProcessDidTerminate

**Comment by SvenTiigi** [comment]
Hi @stormychel,

Thanks for opening up an issue.
As the bug occurred on an unofficially released version of macOS, I will try to reproduce the problem as soon as the official version of macOS Sonoma is released.

**Comment by stormychel** [comment]
Hello @SvenTiigi,

It's an RC, out since September 12th so I don't expect them to change anything before release on September 26th.
Let me know if you need any more info on steps to reproduce or if I can help in any other way.

**Comment by SvenTiigi** [comment]
Hi @stormychel,

I have just tested YouTubePlayerKit on macOS 14.0 (Sonoma) and wasn't able to reproduce your issue.
Could you please provide a minimal example project where the issue can be easily reproduced?

**Comment by stormychel** [comment]
Hello @SvenTiigi thanks for following up and sorry for the late reply.

Here's a quick example: [https://github.com/stormychel/YouTubePlayerKitTest](url)

**Comment by SvenTiigi** [comment]
As the `YouTubePlayer.Error.webContentProcessDidTerminate` is derived from the [WKNavigationDelegate](https://developer.apple.com/documentation/webkit/wknavigationdelegate) callback function [webViewWebContentProcessDidTerminate](https://developer.apple.com/documentation/webkit/wknavigationdelegate/1455639-webviewwebcontentprocessdidtermi) it might be a good idea to use the Console.app to inspect the underlying WebKit logs 🤔

**Comment by stormychel** [comment]
Thanks Sven, will start there!
