### ISSUE TITLE
Sir I have question about views 

### ISSUE THREAD

**Issue by yongbeomkwak** [SvenTiigi/YouTubePlayerKit#73]
### What happened?

Does using the "load" function increase the view count?

### What are the steps to reproduce?

nope

### What is the expected behavior?

Please give me the answer ..

**Comment by SvenTiigi** [comment]
Hi @yongbeomkwak,

Could you please provide a more detailed description of your question/problem?

**Comment by yongbeomkwak** [comment]
oh sorry about that 
i read the youtube document and i got it
