### ISSUE TITLE
Shorts and Live not supported

### ISSUE THREAD

**Issue by mdstage** [SvenTiigi/YouTubePlayerKit#75]
### What happened?

When using URLs leading to short videos or live, the video doesn't play.

Tested in the sample app.

### What are the steps to reproduce?

Short: https://youtube.com/shorts/obxPExZzi5o?si=ujsDo908Dg1J981x
Live: https://www.youtube.com/live/jfKfPfyJRdk?si=w62kL85ADoUnGlOQ

### What is the expected behavior?

Shorts and live URLs playing like other URLs.

**Comment by SvenTiigi** [comment]
Fixed with the latest version [1.5.4](https://github.com/SvenTiigi/YouTubePlayerKit/releases/tag/1.5.4) ✌️
