### ISSUE TITLE
How to play audio when the app is in background mode?

### ISSUE THREAD

**Issue by secret3579** [SvenTiigi/YouTubePlayerKit#8]
## YouTubePlayerKit Environment

- YouTubePlayerKit version: 1.12
- macOS version: 11.5.2
- Xcode version: 13
- Dependency manager (SPM, Manually): SPM

**Comment by SvenTiigi** [comment]
Hi @secret3579,

Playing audio in background or enabling PiP Mode must be enabled via the capabilities of your app.

https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/configuring_the_audio_playback_of_ios_and_tvos_apps

![Screenshot](https://user-images.githubusercontent.com/11733014/140100147-4742e1cf-f23d-40e5-822e-3c2bb4ab4f9b.png)

**Comment by thanhdevapp** [comment]
Now, enable background mode and config session but not work
My update Example project

`//
//  App.swift
//  Example
//
//  Created by Sven Tiigi on 20.09.21.
//

import SwiftUI
import UIKit
import Foundation
import AVFoundation

// MARK: - App

// no changes in your AppDelegate class
class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        print(">> your code here !!")
        let audioSession = AVAudioSession.sharedInstance()
             do {
//                try audioSession.setCategory(.playAndRecord)
//                try audioSession.setCategory(.playback)
                try audioSession.setCategory(.playback, mode: .default)
                try audioSession.setActive(true)
             } catch {
                 print("Setting category to AVAudioSessionCategoryPlayback failed.")
             }
        return true
    }
}

/// The App
@main
struct App {
    // inject into SwiftUI life-cycle via adaptor !!!
    @UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate

}

// MARK: - SwiftUI.App

extension App: SwiftUI.App {
    /// The content and behavior of the app
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
    
}
`

[ProcessSuspension] 0x10c000900 - ProcessAssertion: Failed to acquire RBS assertion 'WebKit Media Playback' for process with PID=2868, error: Error Domain=RBSServiceErrorDomain Code=1 "(originator doesn't have entitlement com.apple.runningboard.assertions.webkit AND originator doesn't have entitlement

**Comment by yongbeomkwak** [comment]
can i play YouTubePlayerKit with AVAudio ??? also in background?
