### ISSUE TITLE
"Always play best video resolution" configuration setting

### ISSUE THREAD

**Issue by nhershy** [SvenTiigi/YouTubePlayerKit#84]
### Is your feature request related to a problem?

No

### What solution would you like?

It appears that videos will play in 720p by default, even if higher resolutions exist (1080p, 4k). Create a configuration param that allows for "possible best" quality when playing videos by default. 

### What alternatives have you considered?

Each time a video plays, user has to manually change resolution to a higher quality using the gear icon

### Any additional context?

N/A

**Comment by SvenTiigi** [comment]
Unfortunately, the YouTube Player iFrame API does not provide a parameter to set the default resolution.
