### ISSUE TITLE
Blurred image when uploading videos from YouTube

### ISSUE THREAD

**Issue by MrJeris** [SvenTiigi/YouTubePlayerKit#85]
### What happened?

Sometimes, when scrolling the feed of a YouTube video, the preview of the video is not fully loaded and remains blurred.
![image_cleanup](https://github.com/SvenTiigi/YouTubePlayerKit/assets/93790505/2090f271-a23d-40e6-bb08-545efa0b1ed5)

### What are the steps to reproduce?

This happens by accident, and there is no obvious pattern to explain why it happens.

### What is the expected behavior?

Is there anyway to make the video preview not blurred or load in normal quality after some time?

**Comment by SvenTiigi** [comment]
The rendered user interface is controlled and managed by the [YouTube Player iFrame API](https://developers.google.com/youtube/iframe_api_reference) please consider to open a bug report at https://developers.google.com/youtube/players/support

**Comment by MrJeris** [comment]
Thank you for the answer.
