### ISSUE TITLE
Support setting up YouTubePlayerWebView with allowsInlineMediaPlayback = false for iPad

### ISSUE THREAD

**Issue by kiddosai** [SvenTiigi/YouTubePlayerKit#89]
### Is your feature request related to a problem?

Yes, allow iPad to support fullscreen mode

### What solution would you like?

From YouTubePlayer configuration dict

### What alternatives have you considered?

None

**Comment by SvenTiigi** [comment]
Duplicate of https://github.com/SvenTiigi/YouTubePlayerKit/issues/52
