### ISSUE TITLE
Should the YouTubePlayer object be held as a @StateObject?

### ISSUE THREAD

**Issue by jackpal** [SvenTiigi/YouTubePlayerKit#9]
I'm not 100% sure on this, but it struck me when I was looking at the Example code:

https://github.com/SvenTiigi/YouTubePlayerKit/blob/9b2c460614f442b6d01f19a087a1abcbb4af3474/Example/Example/ContentView.swift#L17

As I understand it, YouTubePlayer is an ObservableObject, and when observable objects are held in Views, they should be held using @StateObject, to avoid being recreated when the Swift View is recreated.

https://developer.apple.com/documentation/swiftui/stateobject

**Comment by jackpal** [comment]
(I haven't seen many examples where an ObservableObject is held using "let" instead of "var". IDK if that makes a difference.

**Comment by SvenTiigi** [comment]
Hi @jackpal 

Yes, most of the objects which are conform to the `ObservableObject` protocol are also declared as an `@ObservedObject`  inside a SwiftUI View.

In the case of the example app the `@ObservedObject` modifier is not needed as the example App is updating the source directly on the reference of the `YouTubePlayer` so there is no need to tell SwiftUI that the `Body` of the `View` needs to be re-rendered.

The fact that the `YouTubePlayer` is conform to the `ObservableObject` protocol is that if a case would exists where it is truly needed to re-render the `Body` of a `View` then you should mark the `YouTubePlayer` instance with an `@ObservedObject` property wrapper.

**Comment by SvenTiigi** [comment]
Closing this issue for now.
Please feel free to re-open the issue at anytime or open up a PR ✌️
