### ISSUE TITLE
How to use in pod

### ISSUE THREAD

**Issue by Chandresh5245** [SvenTiigi/YouTubePlayerKit#93]
### What happened?

How to use in pod

### What are the steps to reproduce?

How to use in pod

### What is the expected behavior?

How to use in pod

**Comment by SvenTiigi** [comment]
CocoaPods is not supported.
The preferred way of integrating the YouTubePlayerKit to a Xcode project is via the Swift Package Manager.
[Read more](https://github.com/SvenTiigi/YouTubePlayerKit?tab=readme-ov-file#installation)
