### ISSUE TITLE
Build failed because YouTubePlayerKit.swiftmodule is not built for arm64. 

### ISSUE THREAD

**Issue by NorthAustin** [SvenTiigi/YouTubePlayerKit#95]
### What happened?

Received the following error when trying to archive for VisionOS 1.2. 

Build failed because YouTubePlayerKit.swiftmodule is not built for arm64. Please try and run destination with a different architecture. Ensure all targets are configured to build for standard architectures. If your project uses external dependencies, contact those vendors to provide updated copies built to support all architectures.

You can control the visibility of architecture-specific run destinations in the Product > Destination menu.

### What are the steps to reproduce?

Select archive. 

### What is the expected behavior?

archive build

**Comment by SvenTiigi** [comment]
Since the YouTubePlayerKit is a Swift Package cloned and built from source, the origin of this kind of error is more likely related to a misconfiguration within the Xcode project or a different dependency in your project that is a precompiled framework.
