### ISSUE TITLE
Can you remove the who shared the video?

### ISSUE THREAD

**Issue by Bugraciftci** [SvenTiigi/YouTubePlayerKit#96]
### Is your feature request related to a problem?

not a big promblem

### What solution would you like?

user wont go to youtube 

### What alternatives have you considered?

there is no alternative ._. accualy there is an one solution. user can not touch text that whose video

### Any additional context?

no thanks

**Comment by SvenTiigi** [comment]
The rendered user interface is controlled and managed by the [YouTube Player iFrame API](https://developers.google.com/youtube/iframe_api_reference) please consider to open a bug report at https://developers.google.com/youtube/players/support
