### ISSUE TITLE
Custom control with option to hide or disable controls by default iFrame.

### ISSUE THREAD

**Issue by bimal-freebird** [SvenTiigi/YouTubePlayerKit#97]
### Is your feature request related to a problem?

Problem is -
Custom apps should have custom controls.

### What solution would you like?

Should have custom controls .

### What alternatives have you considered?

access the iFrame and create a new iFrame hiding or disabling the defaults controls.

### Any additional context?

No

**Comment by SvenTiigi** [comment]
One of the main goal of this Swift Package is to comply with the [YouTube Terms of Service](https://developers.google.com/youtube/terms/api-services-terms-of-service).
The only allowed user interface must come from the YouTube Player iFrame API, which unfortunately prohibits any custom controls.

**Comment by bimal-freebird** [comment]
https://github.com/PierfrancescoSoffritti/android-youtube-player
