### ISSUE TITLE
Handle YouTube's native "An error occurred."

### ISSUE THREAD

**Issue by artistbuddy** [SvenTiigi/YouTubePlayerKit#99]
### Is your feature request related to a problem?

If URL is not a YouTube one or we persisted some URL and later YouTube deleted such a video, the player state remains ready, but YouTube's native splash screen says error.
<img width="507" alt="Screenshot 2024-07-31 at 21 37 05" src="https://github.com/user-attachments/assets/7777a3c4-0534-4308-9415-358aa3eceedd">

### What solution would you like?

Catch YouTube's native error as player's state error.

### What alternatives have you considered?

I have considered observing getInformation() or getPlaybackMetadata() somehow. If fails it means some error on YouTube side occurred.

**Comment by acosmicflamingo** [comment]
@SvenTiigi can this be fixed with the PR I had opened recently?

**Comment by acosmicflamingo** [comment]
I'm surprised I didn't see a compilation error when I worked on that PR 😕

**Comment by SvenTiigi** [comment]
@artistbuddy thanks for the response! Great to hear you are now receiving an error when passing a a YouTube video url which points to an unavailable or private video.

FYI: The `@MainActor` annotations have been removed

@acosmicflamingo I will implement the Swift 6 complete concurrency checks in a separate feature branch.

**Comment by acosmicflamingo** [comment]
@SvenTiigi sounds good!
